### PR TITLE
fix(readdir): can not readdir on termux(Android)

### PR DESCRIPTION
**Pull request by snowyu**
because there is no /etc/passwd on termux(android).

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c84a83862bcfaefa0b153f0612c075acad76e9df
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/readify

---
This message was auto-generated by https://gitcop.com

**Comment by coderaiser** [comment]
Thank you :), that is definitely a bug, could you please add test case for `android` similar to [windows](https://github.com/coderaiser/readify/blob/v6.2.0/test/readify.js#L252-L273) and [nicki error](https://github.com/coderaiser/readify/blob/v6.2.0/test/readify.js#L429-L446), so there was never errors of such type in a future.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c84a83862bcfaefa0b153f0612c075acad76e9df
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

 * Commit: 8480ee57abd874f2b4c331fb74b79ccb82c97f69
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/readify

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c84a83862bcfaefa0b153f0612c075acad76e9df
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

 * Commit: 8480ee57abd874f2b4c331fb74b79ccb82c97f69
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

 * Commit: bd8c1f8915c0b7c76ea70eb5d1acb3dbfaf7212b
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/readify

---
This message was auto-generated by https://gitcop.com

**Comment by coderaiser** [comment]
Amazing :)👍

**Comment by coderaiser** [comment]
Landed in [v6.2.1](https://github.com/coderaiser/readify/releases/tag/v6.2.1) 🎉.

**Pull request merged**
