### PR TITLE
accent aware sorting

### PR DESCRIPTION
**Pull request by quazardous**

### CODE REVIEW

**Comment by quazardous** [comment]
see #2

**Comment by coderaiser** [comment]
Could you please add test for accents.

**Comment by coderaiser** [comment]
Thank you, merged as 10f9918.

**Comment by quazardous** [comment]
you re welcome !

**Comment by coderaiser** [comment]
There is a problem with accents, after applying sort with `localeCompare` results looks like this:

```js
[
    ".eslintrc",
    ".gitignore",
    ".jscsrc",
    ".jshintrc",
    ".npmignore",
    ".travis.yml",
    "bower.json",
    "ChangeLog",
    "LICENSE",
    "package.json",
    "README.md"
]
```

This is how sort looked like with `a.name > b.name ? 1 : -1`:
```js
[
    ".eslintrc",
    ".gitignore",
    ".jscsrc",
    ".jshintrc",
    ".npmignore",
    ".travis.yml",
    "ChangeLog",
    "LICENSE",
    "README.md",
    "bower.json",
    "package.json"
]
```

Second type is more correct. Do you have any ideas?

**Comment by quazardous** [comment]
capture d ecran de 2017-01-10 17-16-32

case insensitivity seams to be normal on my linux... and it's human friendly....

**Comment by coderaiser** [comment]
`Midnight Commander` sorts files in the same way `Cloud Commander` does with regular sort.
screen shot 2017-01-11 at 10 57 51 am
We should take it into account.

**Comment by quazardous** [comment]
It's a design call :p
Both Nautilus and Windows file explorer are case insensitive and accents aware... I think file commander was designed a long time ago when internationalization was not a concern..

**Comment by quazardous** [comment]
But it's not so important the point is to be able to sort on other file attributes... So I really don't mind either ways.

**Pull request closed without merging**
